import Head from 'next/head'
import {PinDetail,Layout} from '../../components';
import { userInfo } from '../../utils/userInfo';

export default function PinDetails() {
  const user = userInfo();
  
  if(!user) return null;

  return (
    <div>
      <Head>
        <title>Share Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Layout><PinDetail user={user}/></Layout> 
    </div>
  )
}
