import Head from 'next/head'
import {UserProfile} from '../../components';
import { userInfo } from '../../utils/userInfo';


export default function UserId() {
  const user = userInfo(); 
  if(!user) return null;
  
  return (
    <div>
      <Head>
        <title>Share Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <UserProfile user={user}/>
    </div>
  )
}
