import Head from 'next/head'
import {Main,Layout} from '../components';
import { userInfo } from '../utils/userInfo';


export default function Home() {
  const user = userInfo();
  return (
    <div>
      <Head>
        <title>Share Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout><Main user={user}/></Layout>
    </div>
  )
}
